# Generated by Django 5.0.4 on 2024-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_wishlist_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(null=True, to="wishlist.item"),
        ),
    ]
