# Generated by Django 5.0.4 on 2024-11-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0004_item_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(blank=True, to="wishlist.item"),
        ),
    ]
