# Generated by Django 5.0.4 on 2024-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0005_alter_wishlist_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
